/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: parse_proto_google_types.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "parse_proto_google_types.pb-c.h"
void   proto_duration__init
                     (ProtoDuration         *message)
{
  static const ProtoDuration init_value = PROTO_DURATION__INIT;
  *message = init_value;
}
size_t proto_duration__get_packed_size
                     (const ProtoDuration *message)
{
  assert(message->base.descriptor == &proto_duration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_duration__pack
                     (const ProtoDuration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_duration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_duration__pack_to_buffer
                     (const ProtoDuration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_duration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoDuration *
       proto_duration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoDuration *)
     protobuf_c_message_unpack (&proto_duration__descriptor,
                                allocator, len, data);
}
void   proto_duration__free_unpacked
                     (ProtoDuration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_duration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_timestamp__init
                     (ProtoTimestamp         *message)
{
  static const ProtoTimestamp init_value = PROTO_TIMESTAMP__INIT;
  *message = init_value;
}
size_t proto_timestamp__get_packed_size
                     (const ProtoTimestamp *message)
{
  assert(message->base.descriptor == &proto_timestamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_timestamp__pack
                     (const ProtoTimestamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_timestamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_timestamp__pack_to_buffer
                     (const ProtoTimestamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_timestamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoTimestamp *
       proto_timestamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoTimestamp *)
     protobuf_c_message_unpack (&proto_timestamp__descriptor,
                                allocator, len, data);
}
void   proto_timestamp__free_unpacked
                     (ProtoTimestamp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_timestamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_interval__init
                     (ProtoInterval         *message)
{
  static const ProtoInterval init_value = PROTO_INTERVAL__INIT;
  *message = init_value;
}
size_t proto_interval__get_packed_size
                     (const ProtoInterval *message)
{
  assert(message->base.descriptor == &proto_interval__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_interval__pack
                     (const ProtoInterval *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_interval__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_interval__pack_to_buffer
                     (const ProtoInterval *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_interval__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoInterval *
       proto_interval__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoInterval *)
     protobuf_c_message_unpack (&proto_interval__descriptor,
                                allocator, len, data);
}
void   proto_interval__free_unpacked
                     (ProtoInterval *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_interval__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_date__init
                     (ProtoDate         *message)
{
  static const ProtoDate init_value = PROTO_DATE__INIT;
  *message = init_value;
}
size_t proto_date__get_packed_size
                     (const ProtoDate *message)
{
  assert(message->base.descriptor == &proto_date__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_date__pack
                     (const ProtoDate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_date__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_date__pack_to_buffer
                     (const ProtoDate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_date__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoDate *
       proto_date__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoDate *)
     protobuf_c_message_unpack (&proto_date__descriptor,
                                allocator, len, data);
}
void   proto_date__free_unpacked
                     (ProtoDate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_date__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_time_of_day__init
                     (ProtoTimeOfDay         *message)
{
  static const ProtoTimeOfDay init_value = PROTO_TIME_OF_DAY__INIT;
  *message = init_value;
}
size_t proto_time_of_day__get_packed_size
                     (const ProtoTimeOfDay *message)
{
  assert(message->base.descriptor == &proto_time_of_day__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_time_of_day__pack
                     (const ProtoTimeOfDay *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_time_of_day__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_time_of_day__pack_to_buffer
                     (const ProtoTimeOfDay *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_time_of_day__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoTimeOfDay *
       proto_time_of_day__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoTimeOfDay *)
     protobuf_c_message_unpack (&proto_time_of_day__descriptor,
                                allocator, len, data);
}
void   proto_time_of_day__free_unpacked
                     (ProtoTimeOfDay *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_time_of_day__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_field_mask__init
                     (ProtoFieldMask         *message)
{
  static const ProtoFieldMask init_value = PROTO_FIELD_MASK__INIT;
  *message = init_value;
}
size_t proto_field_mask__get_packed_size
                     (const ProtoFieldMask *message)
{
  assert(message->base.descriptor == &proto_field_mask__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_field_mask__pack
                     (const ProtoFieldMask *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_field_mask__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_field_mask__pack_to_buffer
                     (const ProtoFieldMask *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_field_mask__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoFieldMask *
       proto_field_mask__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoFieldMask *)
     protobuf_c_message_unpack (&proto_field_mask__descriptor,
                                allocator, len, data);
}
void   proto_field_mask__free_unpacked
                     (ProtoFieldMask *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_field_mask__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_postal_address__init
                     (ProtoPostalAddress         *message)
{
  static const ProtoPostalAddress init_value = PROTO_POSTAL_ADDRESS__INIT;
  *message = init_value;
}
size_t proto_postal_address__get_packed_size
                     (const ProtoPostalAddress *message)
{
  assert(message->base.descriptor == &proto_postal_address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_postal_address__pack
                     (const ProtoPostalAddress *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_postal_address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_postal_address__pack_to_buffer
                     (const ProtoPostalAddress *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_postal_address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoPostalAddress *
       proto_postal_address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoPostalAddress *)
     protobuf_c_message_unpack (&proto_postal_address__descriptor,
                                allocator, len, data);
}
void   proto_postal_address__free_unpacked
                     (ProtoPostalAddress *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_postal_address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_money__init
                     (ProtoMoney         *message)
{
  static const ProtoMoney init_value = PROTO_MONEY__INIT;
  *message = init_value;
}
size_t proto_money__get_packed_size
                     (const ProtoMoney *message)
{
  assert(message->base.descriptor == &proto_money__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_money__pack
                     (const ProtoMoney *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_money__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_money__pack_to_buffer
                     (const ProtoMoney *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_money__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoMoney *
       proto_money__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoMoney *)
     protobuf_c_message_unpack (&proto_money__descriptor,
                                allocator, len, data);
}
void   proto_money__free_unpacked
                     (ProtoMoney *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_money__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_lat_lng__init
                     (ProtoLatLng         *message)
{
  static const ProtoLatLng init_value = PROTO_LAT_LNG__INIT;
  *message = init_value;
}
size_t proto_lat_lng__get_packed_size
                     (const ProtoLatLng *message)
{
  assert(message->base.descriptor == &proto_lat_lng__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_lat_lng__pack
                     (const ProtoLatLng *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_lat_lng__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_lat_lng__pack_to_buffer
                     (const ProtoLatLng *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_lat_lng__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoLatLng *
       proto_lat_lng__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoLatLng *)
     protobuf_c_message_unpack (&proto_lat_lng__descriptor,
                                allocator, len, data);
}
void   proto_lat_lng__free_unpacked
                     (ProtoLatLng *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_lat_lng__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_color__init
                     (ProtoColor         *message)
{
  static const ProtoColor init_value = PROTO_COLOR__INIT;
  *message = init_value;
}
size_t proto_color__get_packed_size
                     (const ProtoColor *message)
{
  assert(message->base.descriptor == &proto_color__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_color__pack
                     (const ProtoColor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_color__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_color__pack_to_buffer
                     (const ProtoColor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_color__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoColor *
       proto_color__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoColor *)
     protobuf_c_message_unpack (&proto_color__descriptor,
                                allocator, len, data);
}
void   proto_color__free_unpacked
                     (ProtoColor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_color__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto_duration__field_descriptors[2] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(ProtoDuration, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nanos",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtoDuration, nanos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_duration__field_indices_by_name[] = {
  1,   /* field[1] = nanos */
  0,   /* field[0] = seconds */
};
static const ProtobufCIntRange proto_duration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto_duration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoDuration",
  "ProtoDuration",
  "ProtoDuration",
  "",
  sizeof(ProtoDuration),
  2,
  proto_duration__field_descriptors,
  proto_duration__field_indices_by_name,
  1,  proto_duration__number_ranges,
  (ProtobufCMessageInit) proto_duration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_timestamp__field_descriptors[2] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(ProtoTimestamp, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nanos",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtoTimestamp, nanos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_timestamp__field_indices_by_name[] = {
  1,   /* field[1] = nanos */
  0,   /* field[0] = seconds */
};
static const ProtobufCIntRange proto_timestamp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto_timestamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoTimestamp",
  "ProtoTimestamp",
  "ProtoTimestamp",
  "",
  sizeof(ProtoTimestamp),
  2,
  proto_timestamp__field_descriptors,
  proto_timestamp__field_indices_by_name,
  1,  proto_timestamp__number_ranges,
  (ProtobufCMessageInit) proto_timestamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_interval__field_descriptors[2] =
{
  {
    "start_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtoInterval, start_time),
    &proto_timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_time",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtoInterval, end_time),
    &proto_timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_interval__field_indices_by_name[] = {
  1,   /* field[1] = end_time */
  0,   /* field[0] = start_time */
};
static const ProtobufCIntRange proto_interval__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto_interval__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoInterval",
  "ProtoInterval",
  "ProtoInterval",
  "",
  sizeof(ProtoInterval),
  2,
  proto_interval__field_descriptors,
  proto_interval__field_indices_by_name,
  1,  proto_interval__number_ranges,
  (ProtobufCMessageInit) proto_interval__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_date__field_descriptors[3] =
{
  {
    "year",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtoDate, year),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "month",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtoDate, month),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "day",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtoDate, day),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_date__field_indices_by_name[] = {
  2,   /* field[2] = day */
  1,   /* field[1] = month */
  0,   /* field[0] = year */
};
static const ProtobufCIntRange proto_date__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto_date__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoDate",
  "ProtoDate",
  "ProtoDate",
  "",
  sizeof(ProtoDate),
  3,
  proto_date__field_descriptors,
  proto_date__field_indices_by_name,
  1,  proto_date__number_ranges,
  (ProtobufCMessageInit) proto_date__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_time_of_day__field_descriptors[4] =
{
  {
    "hours",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtoTimeOfDay, hours),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minutes",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtoTimeOfDay, minutes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seconds",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtoTimeOfDay, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nanos",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtoTimeOfDay, nanos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_time_of_day__field_indices_by_name[] = {
  0,   /* field[0] = hours */
  1,   /* field[1] = minutes */
  3,   /* field[3] = nanos */
  2,   /* field[2] = seconds */
};
static const ProtobufCIntRange proto_time_of_day__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto_time_of_day__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoTimeOfDay",
  "ProtoTimeOfDay",
  "ProtoTimeOfDay",
  "",
  sizeof(ProtoTimeOfDay),
  4,
  proto_time_of_day__field_descriptors,
  proto_time_of_day__field_indices_by_name,
  1,  proto_time_of_day__number_ranges,
  (ProtobufCMessageInit) proto_time_of_day__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_field_mask__field_descriptors[1] =
{
  {
    "paths",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ProtoFieldMask, n_paths),
    offsetof(ProtoFieldMask, paths),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_field_mask__field_indices_by_name[] = {
  0,   /* field[0] = paths */
};
static const ProtobufCIntRange proto_field_mask__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto_field_mask__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoFieldMask",
  "ProtoFieldMask",
  "ProtoFieldMask",
  "",
  sizeof(ProtoFieldMask),
  1,
  proto_field_mask__field_descriptors,
  proto_field_mask__field_indices_by_name,
  1,  proto_field_mask__number_ranges,
  (ProtobufCMessageInit) proto_field_mask__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_postal_address__field_descriptors[11] =
{
  {
    "revision",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtoPostalAddress, revision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "region_code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoPostalAddress, region_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language_code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoPostalAddress, language_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "postal_code",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoPostalAddress, postal_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sorting_code",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoPostalAddress, sorting_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "administrative_area",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoPostalAddress, administrative_area),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "locality",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoPostalAddress, locality),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sublocality",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoPostalAddress, sublocality),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address_lines",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ProtoPostalAddress, n_address_lines),
    offsetof(ProtoPostalAddress, address_lines),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recipients",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ProtoPostalAddress, n_recipients),
    offsetof(ProtoPostalAddress, recipients),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "organization",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoPostalAddress, organization),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_postal_address__field_indices_by_name[] = {
  8,   /* field[8] = address_lines */
  5,   /* field[5] = administrative_area */
  2,   /* field[2] = language_code */
  6,   /* field[6] = locality */
  10,   /* field[10] = organization */
  3,   /* field[3] = postal_code */
  9,   /* field[9] = recipients */
  1,   /* field[1] = region_code */
  0,   /* field[0] = revision */
  4,   /* field[4] = sorting_code */
  7,   /* field[7] = sublocality */
};
static const ProtobufCIntRange proto_postal_address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor proto_postal_address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoPostalAddress",
  "ProtoPostalAddress",
  "ProtoPostalAddress",
  "",
  sizeof(ProtoPostalAddress),
  11,
  proto_postal_address__field_descriptors,
  proto_postal_address__field_indices_by_name,
  1,  proto_postal_address__number_ranges,
  (ProtobufCMessageInit) proto_postal_address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_money__field_descriptors[3] =
{
  {
    "currency_code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoMoney, currency_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "units",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(ProtoMoney, units),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nanos",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtoMoney, nanos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_money__field_indices_by_name[] = {
  0,   /* field[0] = currency_code */
  2,   /* field[2] = nanos */
  1,   /* field[1] = units */
};
static const ProtobufCIntRange proto_money__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto_money__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoMoney",
  "ProtoMoney",
  "ProtoMoney",
  "",
  sizeof(ProtoMoney),
  3,
  proto_money__field_descriptors,
  proto_money__field_indices_by_name,
  1,  proto_money__number_ranges,
  (ProtobufCMessageInit) proto_money__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_lat_lng__field_descriptors[2] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ProtoLatLng, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ProtoLatLng, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_lat_lng__field_indices_by_name[] = {
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
};
static const ProtobufCIntRange proto_lat_lng__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto_lat_lng__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoLatLng",
  "ProtoLatLng",
  "ProtoLatLng",
  "",
  sizeof(ProtoLatLng),
  2,
  proto_lat_lng__field_descriptors,
  proto_lat_lng__field_indices_by_name,
  1,  proto_lat_lng__number_ranges,
  (ProtobufCMessageInit) proto_lat_lng__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_color__field_descriptors[4] =
{
  {
    "red",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtoColor, red),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "green",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtoColor, green),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blue",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtoColor, blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alpha",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtoColor, alpha),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_color__field_indices_by_name[] = {
  3,   /* field[3] = alpha */
  2,   /* field[2] = blue */
  1,   /* field[1] = green */
  0,   /* field[0] = red */
};
static const ProtobufCIntRange proto_color__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto_color__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoColor",
  "ProtoColor",
  "ProtoColor",
  "",
  sizeof(ProtoColor),
  4,
  proto_color__field_descriptors,
  proto_color__field_indices_by_name,
  1,  proto_color__number_ranges,
  (ProtobufCMessageInit) proto_color__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue month__enum_values_by_number[13] =
{
  { "MONTH_UNSPECIFIED", "MONTH__MONTH_UNSPECIFIED", 0 },
  { "JANUARY", "MONTH__JANUARY", 1 },
  { "FEBRUARY", "MONTH__FEBRUARY", 2 },
  { "MARCH", "MONTH__MARCH", 3 },
  { "APRIL", "MONTH__APRIL", 4 },
  { "MAY", "MONTH__MAY", 5 },
  { "JUNE", "MONTH__JUNE", 6 },
  { "JULY", "MONTH__JULY", 7 },
  { "AUGUST", "MONTH__AUGUST", 8 },
  { "SEPTEMBER", "MONTH__SEPTEMBER", 9 },
  { "OCTOBER", "MONTH__OCTOBER", 10 },
  { "NOVEMBER", "MONTH__NOVEMBER", 11 },
  { "DECEMBER", "MONTH__DECEMBER", 12 },
};
static const ProtobufCIntRange month__value_ranges[] = {
{0, 0},{0, 13}
};
static const ProtobufCEnumValueIndex month__enum_values_by_name[13] =
{
  { "APRIL", 4 },
  { "AUGUST", 8 },
  { "DECEMBER", 12 },
  { "FEBRUARY", 2 },
  { "JANUARY", 1 },
  { "JULY", 7 },
  { "JUNE", 6 },
  { "MARCH", 3 },
  { "MAY", 5 },
  { "MONTH_UNSPECIFIED", 0 },
  { "NOVEMBER", 11 },
  { "OCTOBER", 10 },
  { "SEPTEMBER", 9 },
};
const ProtobufCEnumDescriptor month__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Month",
  "Month",
  "Month",
  "",
  13,
  month__enum_values_by_number,
  13,
  month__enum_values_by_name,
  1,
  month__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue day_of_week__enum_values_by_number[8] =
{
  { "DAY_OF_WEEK_UNSPECIFIED", "DAY_OF_WEEK__DAY_OF_WEEK_UNSPECIFIED", 0 },
  { "MONDAY", "DAY_OF_WEEK__MONDAY", 1 },
  { "TUESDAY", "DAY_OF_WEEK__TUESDAY", 2 },
  { "WEDNESDAY", "DAY_OF_WEEK__WEDNESDAY", 3 },
  { "THURSDAY", "DAY_OF_WEEK__THURSDAY", 4 },
  { "FRIDAY", "DAY_OF_WEEK__FRIDAY", 5 },
  { "SATURDAY", "DAY_OF_WEEK__SATURDAY", 6 },
  { "SUNDAY", "DAY_OF_WEEK__SUNDAY", 7 },
};
static const ProtobufCIntRange day_of_week__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex day_of_week__enum_values_by_name[8] =
{
  { "DAY_OF_WEEK_UNSPECIFIED", 0 },
  { "FRIDAY", 5 },
  { "MONDAY", 1 },
  { "SATURDAY", 6 },
  { "SUNDAY", 7 },
  { "THURSDAY", 4 },
  { "TUESDAY", 2 },
  { "WEDNESDAY", 3 },
};
const ProtobufCEnumDescriptor day_of_week__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DayOfWeek",
  "DayOfWeek",
  "DayOfWeek",
  "",
  8,
  day_of_week__enum_values_by_number,
  8,
  day_of_week__enum_values_by_name,
  1,
  day_of_week__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
