/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tests_proto_types.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tests_proto_types.pb-c.h"
void   proto_file_header__init
                     (ProtoFileHeader         *message)
{
  static const ProtoFileHeader init_value = PROTO_FILE_HEADER__INIT;
  *message = init_value;
}
size_t proto_file_header__get_packed_size
                     (const ProtoFileHeader *message)
{
  assert(message->base.descriptor == &proto_file_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_file_header__pack
                     (const ProtoFileHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_file_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_file_header__pack_to_buffer
                     (const ProtoFileHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_file_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoFileHeader *
       proto_file_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoFileHeader *)
     protobuf_c_message_unpack (&proto_file_header__descriptor,
                                allocator, len, data);
}
void   proto_file_header__free_unpacked
                     (ProtoFileHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_file_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue proto_file_header__file_type__enum_values_by_number[4] =
{
  { "NONE", "PROTO_FILE_HEADER__FILE_TYPE__NONE", 0 },
  { "PNG", "PROTO_FILE_HEADER__FILE_TYPE__PNG", 1 },
  { "JPEG", "PROTO_FILE_HEADER__FILE_TYPE__JPEG", 2 },
  { "GIF", "PROTO_FILE_HEADER__FILE_TYPE__GIF", 3 },
};
static const ProtobufCIntRange proto_file_header__file_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex proto_file_header__file_type__enum_values_by_name[4] =
{
  { "GIF", 3 },
  { "JPEG", 2 },
  { "NONE", 0 },
  { "PNG", 1 },
};
const ProtobufCEnumDescriptor proto_file_header__file_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ProtoFileHeader.FileType",
  "FileType",
  "ProtoFileHeader__FileType",
  "",
  4,
  proto_file_header__file_type__enum_values_by_number,
  4,
  proto_file_header__file_type__enum_values_by_name,
  1,
  proto_file_header__file_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const int32_t proto_file_header__new_field__default_value = -1;
static const ProtobufCFieldDescriptor proto_file_header__field_descriptors[16] =
{
  {
    "v_double",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_double),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_float",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_float),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_int32",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_int32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_int64",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_int64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_uint32",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_uint32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_uint64",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_uint64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_sint32",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_sint32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_sint64",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_sint64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_fixed32",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_fixed32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_fixed64",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_fixed64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_sfixed32",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SFIXED32,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_sfixed32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_sfixed64",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SFIXED64,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_sfixed64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_bool",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_bool),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_file_type",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_file_type),
    &proto_file_header__file_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_field",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ProtoFileHeader, has_new_field),
    offsetof(ProtoFileHeader, new_field),
    NULL,
    &proto_file_header__new_field__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v_string",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoFileHeader, v_string),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_file_header__field_indices_by_name[] = {
  14,   /* field[14] = new_field */
  12,   /* field[12] = v_bool */
  0,   /* field[0] = v_double */
  13,   /* field[13] = v_file_type */
  8,   /* field[8] = v_fixed32 */
  9,   /* field[9] = v_fixed64 */
  1,   /* field[1] = v_float */
  2,   /* field[2] = v_int32 */
  3,   /* field[3] = v_int64 */
  10,   /* field[10] = v_sfixed32 */
  11,   /* field[11] = v_sfixed64 */
  6,   /* field[6] = v_sint32 */
  7,   /* field[7] = v_sint64 */
  15,   /* field[15] = v_string */
  4,   /* field[4] = v_uint32 */
  5,   /* field[5] = v_uint64 */
};
static const ProtobufCIntRange proto_file_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor proto_file_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoFileHeader",
  "ProtoFileHeader",
  "ProtoFileHeader",
  "",
  sizeof(ProtoFileHeader),
  16,
  proto_file_header__field_descriptors,
  proto_file_header__field_indices_by_name,
  1,  proto_file_header__number_ranges,
  (ProtobufCMessageInit) proto_file_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
