/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tests_proto_types.proto */

#ifndef PROTOBUF_C_tests_5fproto_5ftypes_2eproto__INCLUDED
#define PROTOBUF_C_tests_5fproto_5ftypes_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct ProtoFileHeader ProtoFileHeader;


/* --- enums --- */

typedef enum _ProtoFileHeader__FileType {
  PROTO_FILE_HEADER__FILE_TYPE__NONE = 0,
  PROTO_FILE_HEADER__FILE_TYPE__PNG = 1,
  PROTO_FILE_HEADER__FILE_TYPE__JPEG = 2,
  PROTO_FILE_HEADER__FILE_TYPE__GIF = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO_FILE_HEADER__FILE_TYPE)
} ProtoFileHeader__FileType;

/* --- messages --- */

struct  ProtoFileHeader
{
  ProtobufCMessage base;
  double v_double;
  float v_float;
  int32_t v_int32;
  int64_t v_int64;
  uint32_t v_uint32;
  uint64_t v_uint64;
  int32_t v_sint32;
  int64_t v_sint64;
  uint32_t v_fixed32;
  uint64_t v_fixed64;
  int32_t v_sfixed32;
  int64_t v_sfixed64;
  protobuf_c_boolean v_bool;
  ProtoFileHeader__FileType v_file_type;
  protobuf_c_boolean has_new_field;
  int32_t new_field;
  char *v_string;
};
#define PROTO_FILE_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto_file_header__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, PROTO_FILE_HEADER__FILE_TYPE__NONE, 0, -1, NULL }


/* ProtoFileHeader methods */
void   proto_file_header__init
                     (ProtoFileHeader         *message);
size_t proto_file_header__get_packed_size
                     (const ProtoFileHeader   *message);
size_t proto_file_header__pack
                     (const ProtoFileHeader   *message,
                      uint8_t             *out);
size_t proto_file_header__pack_to_buffer
                     (const ProtoFileHeader   *message,
                      ProtobufCBuffer     *buffer);
ProtoFileHeader *
       proto_file_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto_file_header__free_unpacked
                     (ProtoFileHeader *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ProtoFileHeader_Closure)
                 (const ProtoFileHeader *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto_file_header__descriptor;
extern const ProtobufCEnumDescriptor    proto_file_header__file_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_tests_5fproto_5ftypes_2eproto__INCLUDED */
