/*
File:   resources_zip.h
Author: WARNING: This file is generated by pig_build.exe! Any hand edits will be lost!
*/

#ifndef _RESOURCES_ZIP_H
#define _RESOURCES_ZIP_H

u8 resources_zip_bytes[383164];

#endif //_RESOURCES_ZIP_H
